# Generated by Django 3.2.12 on 2022-04-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Service'), ('I', 'Inventory'), ('N', 'Non-Inventory')], max_length=10, verbose_name='Type')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('parent', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('master_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Master Part Number')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Price')),
                ('measurement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Measurement')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='NonInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('master_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Master Part Number')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Price')),
                ('measurement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Measurement')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='MasterPartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_part_number', models.CharField(max_length=200, verbose_name='Master Part Number')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufacturer')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('measurement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Measurement')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory')),
                ('primary_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Price')),
                ('measurement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Measurement')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('inventory_qty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Inventory Qty')),
                ('inventory_correction', models.CharField(blank=True, max_length=100, null=True, verbose_name='Inventory Correction')),
                ('inventory_correction_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory')),
                ('master_part_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.masterpartnumber')),
            ],
        ),
    ]
