# Generated by Django 3.2.12 on 2022-04-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('customers', '0003_auto_20220406_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder', models.CharField(max_length=100, verbose_name='Workorder')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('deadline', models.CharField(blank=True, max_length=100, null=True, verbose_name='Deadline')),
                ('budget', models.CharField(blank=True, max_length=100, null=True, verbose_name='Budget')),
                ('quoted_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quoted Price')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkorderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('billable_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Billable Time')),
                ('default_rate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Default Rate')),
                ('custom_rate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Custom Rate')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.service')),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkorderNonInventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('qty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Price')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.noninventory')),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkorderInventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('qty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Price')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory')),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.workorder')),
            ],
        ),
    ]
