# Generated by Django 3.2.12 on 2022-04-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20220406_1928'),
        ('workorders', '0002_alter_workorder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.contact'),
        ),
    ]
