# Generated by Django 3.2.12 on 2022-05-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_workorder_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='workorder',
            field=models.CharField(max_length=100, unique=True, verbose_name='Workorder'),
        ),
    ]
