# Generated by Django 3.2.12 on 2022-04-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField(auto_now=True)),
                ('vendor_order_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Order Number')),
                ('vendor_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Part Number')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('qty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty')),
                ('item_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Price')),
                ('pkg_qty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Package Qty')),
                ('shipping_cost', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping Cost')),
                ('tax', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax')),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('date_received', models.DateTimeField(auto_now=True)),
                ('internal_part_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.masterpartnumber')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
