# Generated by Django 3.2.12 on 2022-04-20 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('inventory', '0001_initial'),
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseOrder2',
            new_name='PurchaseOrder',
        ),
    ]
